#version 450
#include "fbm.glsl"

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

struct Vertex
{
    vec4 pos_xyz_norm_x;
    vec4 norm_yz_uv;
};

layout(set = 0, binding = 0, std430) writeonly buffer VerticesBuf
{
    Vertex v[];
} vertices;

layout(set = 0, binding = 1, std430) writeonly buffer IndicesBuf
{
    uint i[];
} indices;

layout(set = 0, binding = 2, r8) uniform writeonly image2D height_map;

layout(push_constant) uniform PC
{
    uint  width;
    uint  height;
    uint  seed;

    vec2  offset;
    float spacing;

    uint  num_layers;
    float base_freq;
    float lacunarity;
    float persistence;

    float height_scale;
    float domain_warp;
} pc;

uint vid(uint x, uint y) { return y * pc.width + x; }

void main()
{
    uvec2 gid = gl_GlobalInvocationID.xy;
    uint x = gid.x;
    uint y = gid.y;

    if (x >= pc.width || y >= pc.height) return;

    uint v_index = vid(x, y);

    float half_w = float(pc.width  - 1u) * 0.5 * pc.spacing;
    float half_h = float(pc.height - 1u) * 0.5 * pc.spacing;

    float fx = float(x) * pc.spacing - half_w;
    float fz = float(y) * pc.spacing - half_h;

    vec2 np = vec2(fx, fz) + pc.offset;
    float h = fbm(
        np,
        pc.base_freq,
        pc.num_layers,
        pc.lacunarity,
        pc.persistence,
        pc.domain_warp,
        pc.seed
    ) * pc.height_scale;

    vec3 pos = vec3(fx, h, fz);
    imageStore(height_map, ivec2(gid), vec4(h / pc.height_scale * 0.5f + 0.5f, 0.0f, 0.0f, 0.0f));

    // temporary normal (will be overwritten in stage 2)
    vec3 nrm = vec3(0.0, 1.0, 0.0);

    vec2 uv = vec2(
        float(x) / float(pc.width  - 1u),
        float(y) / float(pc.height - 1u)
    );

    Vertex outv;
    outv.pos_xyz_norm_x = vec4(pos, nrm.x);
    outv.norm_yz_uv     = vec4(nrm.yz, uv.xy);
    vertices.v[v_index] = outv;

    if (x < pc.width - 1u && y < pc.height - 1u)
    {
        uint i_index = (y * (pc.width - 1u) + x) * 6u;

        uint v00 = vid(x,      y);
        uint v10 = vid(x + 1u, y);
        uint v01 = vid(x,      y + 1u);
        uint v11 = vid(x + 1u, y + 1u);

        indices.i[i_index + 0u] = v00;
        indices.i[i_index + 1u] = v10;
        indices.i[i_index + 2u] = v01;

        indices.i[i_index + 3u] = v10;
        indices.i[i_index + 4u] = v11;
        indices.i[i_index + 5u] = v01;
    }
}
