#version 450
#include "../common/fbm.glsl"

layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout(set = 0, binding = 0, r8) uniform writeonly image3D terrain_density_tex;

layout(push_constant) uniform PC
{
    float base_freq;
    uint  num_layers;
    float lacunarity;
    float persistence;
    float domain_warp;
    uint  seed;
    uvec3 world_grid_size;
    ivec3 chunk_offset;
} pc;

void main()
{
    ivec3 gid = ivec3(gl_GlobalInvocationID.xyz);

    ivec3 size = imageSize(terrain_density_tex);
    if (any(greaterThanEqual(gid, size))) return;

    vec3 uvw = (vec3(gid) + vec3(pc.chunk_offset)) / vec3(pc.world_grid_size - uvec3(1u));
    vec3 p = uvw - 0.5;

    float cave_noise = fbm3(
        p,
        pc.base_freq,
        max(pc.num_layers - 1u, 1u),
        pc.lacunarity,
        pc.persistence,
        pc.domain_warp * 0.65,
        pc.seed
    ) * 0.5 + 0.5;

    imageStore(terrain_density_tex, gid, vec4(clamp(cave_noise, 0.0, 1.0), 0.0, 0.0, 0.0));
}