#version 450

#include "../common/fbm.glsl"

layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout(set = 0, binding = 0, r8) uniform writeonly image3D terrain_density;

layout(push_constant) uniform PC
{
    uvec3 world_point_count;
    ivec3 chunk_sample_offset;
} pc;

void main()
{
    ivec3 gid = ivec3(gl_GlobalInvocationID.xyz);

    ivec3 size = imageSize(terrain_density);
    if (any(greaterThanEqual(gid, size))) return;

    vec3 world_size = vec3(pc.world_point_count - uvec3(1u));
    vec3 world_pos = vec3(gid + pc.chunk_sample_offset);
    vec3 world_center = world_size * 0.5;

    float half_extent = 0.5 * min(world_size.x, min(world_size.y, world_size.z));
    float base_radius = half_extent * 0.8;
    float surface_blend = 2.0;

    vec3 p = world_pos - world_center;

    float noise = fbm3(
        normalize(p) * 2.0,
        1.0,
        5u,
        2.0,
        0.5,
        0.0,
        1337u
    );

    float terrain_height = noise * 64.0;
    float sphere_radius = base_radius + terrain_height;

    float density = smoothstep(
        -surface_blend,
        surface_blend,
        sphere_radius - length(p)
    );

    imageStore(terrain_density, gid, vec4(density, 0.0, 0.0, 0.0));
}
